apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: myapp
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      nodePort: 30180
  type: NodePort
